
replicaCount: 1

image:
  repository: 43.205.113.13/smart-task/report-service
  tag: "23"
  pullPolicy: Always

imagePullSecrets: []

service:
  type: ClusterIP
  port: 5004
  targetPort: 5004

containerPort: 5004

resources: {}

env:
  PORT: "5004"

ingress:
  enabled: true
  className: nginx

  host: report.smarttask.local

  path: /

  pathType: Prefix
