apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notification-service.selectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "smart-task"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-mongodb: "smart-task/data/mongodb"
        vault.hashicorp.com/agent-inject-template-mongodb: |
          {{ "{{- with secret \"smart-task/data/mongodb\" -}}" }}
          export MONGO_URI="{{ "{{ .Data.data.NOTIFICATION_MONGO_URI }}" }}"
          {{ "{{- end }}" }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: notification-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - "set -a; . /vault/secrets/mongodb; set +a; npm start"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
