replicaCount: 1

image:
  repository: 43.205.113.13/smart-task/auth-service
  tag: "23"
  pullPolicy: Always

imagePullSecrets: []

service:
  type: ClusterIP
  port: 5001
  targetPort: 5001

containerPort: 5001

resources: {}

env:
  PORT: "5001"
  JWT_EXPIRES_IN: "1d"

ingress:
  enabled: true
  className: nginx

  host: auth.smarttask.local

  path: /

  pathType: Prefix
