replicaCount: 1

image:
  repository: 43.205.113.13/smart-task/notification-service
  tag: "23"
  pullPolicy: Always

imagePullSecrets: []

service:
  type: ClusterIP
  port: 5003
  targetPort: 5003

containerPort: 5003

resources: {}

env:
  PORT: "5003"

ingress:
  enabled: true
  className: nginx

  host: notification.smarttask.local

  path: /

  pathType: Prefix
